// <auto-generated />
using System;
using CSharpSecaoDezoito.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSharpSecaoDezoito.Migrations
{
    [DbContext(typeof(CSharpSecaoDezoitoContext))]
    [Migration("20220212152731_OtherEntities")]
    partial class OtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CSharpSecaoDezoito.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CSharpSecaoDezoito.Models.SalesRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SellerSRId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellerSRId");

                    b.ToTable("SalesRecord");
                });

            modelBuilder.Entity("CSharpSecaoDezoito.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BaseSalary")
                        .HasColumnType("double");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartmentSId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentSId");

                    b.ToTable("Seller");
                });

            modelBuilder.Entity("CSharpSecaoDezoito.Models.SalesRecord", b =>
                {
                    b.HasOne("CSharpSecaoDezoito.Models.Seller", "SellerSR")
                        .WithMany("Sales")
                        .HasForeignKey("SellerSRId");
                });

            modelBuilder.Entity("CSharpSecaoDezoito.Models.Seller", b =>
                {
                    b.HasOne("CSharpSecaoDezoito.Models.Department", "DepartmentS")
                        .WithMany("Sellers")
                        .HasForeignKey("DepartmentSId");
                });
#pragma warning restore 612, 618
        }
    }
}
